;; list of packages to auto-install

(defvar user-packages
  '(
    ace-jump-mode
    ack-and-a-half
    auto-complete
    autopair
    dash
    diminish
    emacs-eclim
    emmet-mode
    evil
    evil-indent-textobject
    evil-leader
    evil-matchit
    evil-nerd-commenter
    evil-numbers
    expand-region
    flycheck
    ggtags
    ido
    ido-hacks
    ido-ubiquitous
    ido-vertical-mode
    imenu-anywhere
    jedi
    ac-js2
    js2-mode
    key-chord
    magit
    multi-term
    multiple-cursors
    projectile
    pymacs
    s
    shell-pop
    smex
    surround
    window-numbering
    yasnippet
  ))
